version: '3'

services:
  redis-stack:
    image: redis/redis-stack:latest
    container_name: redis-stack
    ports:
      - "6379:6379" # Redis Stack server port
    volumes:
      - ./local-data:/data # Persist data to a local directory
      - ./local-redis-stack.conf:/redis-stack.conf # Use a local configuration file
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
  
  mysql:
    image: mysql:latest
    container_name: mysql-container
    environment:
      - MYSQL_ROOT_PASSWORD=1234 # Change this to a secure password
      - MYSQL_DATABASE=veh # Optional: name of the database to create
    ports:
      - "3306:3306" # Expose MySQL port
    volumes:
      - ./mysql-data:/var/lib/mysql # Persist MySQL data to a local directory
